---
title: "Planes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Planes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(g2r)
```

```{r}
diamonds <- jsonlite::fromJSON(
  "https://gw.alipayobjects.com/os/antvdemo/assets/data/diamond.json"
)
```

## Rect

Recreation of [this example](https://g2.antv.vision/en/examples/facet/facet#column).

```{r}
g2(diamonds, asp(carat, price, color = clarity)) %>% 
  fig_point(
    asp(shape = "circle", size = 3),
    fillOpacity = 0.3, stroke = 0
  ) %>% 
  planes(~cut, type = "rect") %>% 
  motif(padding = c(32, 8, 48, 48))
```

Recreation of [this example](https://g2.antv.vision/en/examples/facet/facet#rect).

```{r}
g2(diamonds, asp(carat, price, color = cut)) %>% 
  fig_point(
    asp(shape = "circle", size = 3),
    fillOpacity = 0.3, stroke = 0
  ) %>% 
  planes(~cut+clarity, type = "rect") %>% 
  motif(padding = c(32, 8, 48, 48))
```

## List

Recreation of [this example](https://g2.antv.vision/en/examples/facet/facet#list).

```{r}
g2(diamonds, asp(carat, price, color = cut)) %>% 
  fig_point(
    asp(shape = "circle", size = 3),
    fillOpacity = 0.3, stroke = 0
  ) %>% 
  planes(
    ~cut, 
    type = "list",
    cols = 3,
    padding = 30
  ) %>% 
  motif(padding = c(32, 8, 48, 48))
```

## Circle

```{r}
df <- diamonds %>% 
  dplyr::group_by(clarity, cut) %>% 
  dplyr::summarise(
    price = sum(price)
  )

total <- df %>% 
  dplyr::group_by(clarity) %>% 
  dplyr::summarise(
    total = sum(price)
  )

df <- df %>% 
  dplyr::left_join(total, by = "clarity") %>% 
  dplyr::mutate(price = price / total)

g2(df, asp(y = price, color = cut)) %>% 
  fig_interval(
    adjust("stack"),
    stroke = "#fff", lineWidth = 2
  ) %>% 
  coord_type("theta", innerRadius = .2) %>% 
  planes(~clarity, type = "circle")
```

## Mirror

Recreation of [this example](https://g2.antv.vision/en/examples/facet/facet#mirror-transpose)

```{r}
df <- data.frame(
  x = rep(1:50, 2),
  y = c(cars$speed, cars$dist),
  grp = rep(c("Speed", "Dist"), each = 50)
)

g2(df, asp(x, y, color = grp)) %>% 
  fig_interval() %>% 
  planes(
    ~grp, 
    padding = c(0, 48, 0, 0),
    type = "mirror", 
    transpose = TRUE
  ) %>% 
  motif(padding = c(32, 16, 48, 16))
```

## Tree

```{r}
g2(iris, asp(Petal.Width, Petal.Length, color = Species)) %>% 
  fig_point() %>% 
  planes(~Species, type = "tree")
```
