---
title: "Quick Plots"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quick Plots}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(g2r)
```

The `qg2` function allows quickly drawing plots from different types of objects. If you want to reproduce these but have more control on the chart (color, etc.) then please see the [recipes vignette](/articles/recipes) vignettes.

## Dot and whisker

```{r}
m1 <- lm(mpg ~ wt + cyl + disp + gear, data = mtcars)

qg2(m1)
```

```{r}
m2 <- update(m1, . ~ . + hp)
m3 <- update(m2, . ~ . + am) 

qg2(list(m1, m2, m3))
```

## Survival

```{r}
library(survival)

data(veteran)

fit <- survfit(Surv(time, status) ~ trt, data = veteran)

qg2(fit)
```

## Acf

```{r}
cc <- acf(lh, plot = FALSE)

qg2(cc)
```

## Xts

```{r, warning=FALSE, message=FALSE, error=FALSE}
library(quantmod)

aapl <- getSymbols("AAPL", env = NULL)

aapl %>% 
  head(50) %>% 
  qg2()
```

```{r}
rate <- getFX("EUR/CHF", auto.assign = FALSE)

qg2(rate)
```

## stl

```{r}
s <- stl(nottem, "per")

qg2(s)
```

## Roc curve

```{r}
library(yardstick)

data(two_class_example)

roc <- roc_curve(two_class_example, truth, Class1)

qg2(roc)
```

```{r}
data(hpc_cv)

hpc_cv %>%
  dplyr::group_by(Resample) %>%
  roc_curve(obs, VF:L) %>% 
  qg2()
```

## Forecast

```{r, message=FALSE, warning=FALSE, error=FALSE}
library(forecast)

fc <- forecast(ets(USAccDeaths))

qg2(fc)
```

## Matrices

```{r}
correl_mat <- cor(mtcars)

qg2(correl_mat) %>% 
  gauge_color(c("#c77dff", "#7b2cbf", "#240046"))
```

## igraph

```{r}
g <- igraph::erdos.renyi.game(500, 2/500)

qg2(g)
```

## PCA

```{r}
pca <- prcomp(mtcars[,c(1:7,10,11)], center = TRUE,scale. = TRUE)

qg2(pca)
```

<a class="btn btn-default" href="recipe.html">Explore recipe</a>
